git-overview: Offer multiple output formats
"fixes" is the format recommended in Documentation/submitting-patches.rst
for "Fixes:" commit tags.

diff --git a/git-overview b/git-overview
--- a/git-overview
+++ b/git-overview
@@ -1,17 +1,83 @@
-#!/bin/bash -e
+#!/bin/bash
 
-if [ $# -eq 0 ]; then
-	set -- "HEAD"
+progname=$(basename "$0")
+format=short
+
+usage () {
+	echo "Usage: git overview <commit...>"
+	echo ""
+	echo "Output a summary string of commit objects"
+	echo ""
+	echo "Options:"
+	echo "    -s, --short         Use format <abbrev> <subject> (<desc>) [default]"
+	echo "    -f, --fixes         Use format <abbrev12> (\"<subject>\")"
+	echo "    -l, --long          Use format <abbrev12> (\"<subject>\", <desc>)"
+	echo "    -h, --help          Print this help"
+	echo ""
+}
+
+result=$(getopt -o sflh --long short,fixes,long,help -n "$progname" -- "$@")
+retval=$?
+if [ $retval -eq 1 ]; then
+	usage > /dev/stderr
+	exit 1
+elif [ $retval -ne 0 ]; then
+	echo "Error: getopt error ($retval)" > /dev/stderr
+	exit 1
 fi
 
-if [ $(git rev-parse "$@" 2>/dev/null | wc -l) -eq 1 ]; then
-	limit="-n1"
+eval set -- "$result"
+
+while true ; do
+	case "$1" in
+		-s|--short)
+					format=short
+					;;
+		-f|--fixes)
+					format=fixes
+					;;
+		-l|--long)
+					format=long
+					;;
+                -h|--help)
+					usage
+					exit
+					;;
+		--)
+					shift
+					break
+					;;
+		*)
+					echo "Error: could not parse arguments" >&2
+					exit 1
+					;;
+	esac
+	shift
+done
+
+revs=$(git rev-parse --default HEAD "$@")
+if [ $(echo "$revs" | wc -l) -eq 1 ]; then
+	limit="--max-count=1"
 fi
 
-git rev-list $limit "$@" | while read commit; do
-	git_describe=$(git describe --contains --match "v*" $commit 2>/dev/null || true)
-	if [ -z "$git_describe" ]; then
-		git_describe=$(git describe --contains --all $commit)
+echo "$revs" | git rev-list $limit --stdin | while read commit; do
+	if [ $format = "short" -o $format = "long" ]; then
+		desc=$(git describe --contains --match "v*" $commit 2>/dev/null)
+		if [ -z "$desc" ]; then
+			desc=$(git describe --contains --all $commit)
+		fi
+		desc="${desc%%[~^]*}"
 	fi
-	echo "$(git log -n1 --pretty="format:%h %s" $commit) (${git_describe%%[~^]*})"
+
+	case $format in
+		short)
+			echo "$(git log --max-count=1 --pretty="format:%h %s" $commit) ($desc)"
+			;;
+		fixes)
+			echo "$(git log --max-count=1 --abbrev=12 --pretty="format:%h (\"%s\")" $commit)"
+			;;
+		long)
+			echo "$(git log --max-count=1 --abbrev=12 --pretty="format:%h (\"%s\"" $commit), $desc)"
+			;;
+	esac
 done
